<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comptype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Comptype_model');
    } 

    /*
     * Listing of comptypes
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('comptype/index?');
        $config['total_rows'] = $this->Comptype_model->get_all_comptypes_count();
        $this->pagination->initialize($config);

        $data['comptypes'] = $this->Comptype_model->get_all_comptypes($params);
        
        $data['_view'] = 'comptype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new comptype
     */
    function add()
    {   if(!$this->auth->isAdd()){
            redirect('/');
        }
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'Name' => $this->input->post('Name'),
            );
            
            $comptype_id = $this->Comptype_model->add_comptype($params);
            redirect('comptype/index');
        }
        else
        {            
            $data['_view'] = 'comptype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a comptype
     */
    function edit($CompType)
    {   
        if(!$this->auth->isEdit()){
            redirect('/');
        }
        // check if the comptype exists before trying to edit it
        $data['comptype'] = $this->Comptype_model->get_comptype($CompType);
        
        if(isset($data['comptype']['CompType']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'Name' => $this->input->post('Name'),
                );

                $this->Comptype_model->update_comptype($CompType,$params);            
                redirect('comptype/index');
            }
            else
            {
                $data['_view'] = 'comptype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The comptype you are trying to edit does not exist.');
    } 

    /*
     * Deleting comptype
     */
    function remove($CompType)
    {
        if(!$this->auth->isDelete()){
            redirect('/');
        }
        $comptype = $this->Comptype_model->get_comptype($CompType);

        // check if the comptype exists before trying to delete it
        if(isset($comptype['CompType']))
        {
            $this->Comptype_model->delete_comptype($CompType);
            redirect('comptype/index');
        }
        else
            show_error('The comptype you are trying to delete does not exist.');
    }
    
}
