<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
		$this->load->model('Customer_model');
        $this->load->model('Company_model');
        $this->load->model('Document_model');
        
    }

    function index()
    {
		
		$Search=$this->input->post('Search');
		
		$data['_view'] = 'dashboard';
        $data['total_customer'] = $this->Customer_model->get_all_customers_count();
        $data['total_company'] = $this->Company_model->get_all_company_count();
        $data['total_document'] = $this->Document_model->get_all_documents_count();
        $data['total_document_expire'] = $this->Document_model->get_expire_documents_count();
		     
        $this->load->view('layouts/main',$data);
    }
}
