<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dcategory extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dcategory_model');
    } 

    /*
     * Listing of dcategory
     */
    function index()
    {
        $data['dcategory'] = $this->Dcategory_model->get_all_dcategory();
        
        $data['_view'] = 'dcategory/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new dcategory
     */
    function add()
    {   
        if(!$this->auth->isAdd()){
            redirect('/');
        }
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $dcategory_id = $this->Dcategory_model->add_dcategory($params);
            redirect('dcategory/index');
        }
        else
        {            
            $data['_view'] = 'dcategory/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a dcategory
     */
    function edit($dtype)
    {   
        if(!$this->auth->isEdit()){
            redirect('/');
        }
        // check if the dcategory exists before trying to edit it
        $data['dcategory'] = $this->Dcategory_model->get_dcategory($dtype);
        
        if(isset($data['dcategory']['dtype']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Dcategory_model->update_dcategory($dtype,$params);            
                redirect('dcategory/index');
            }
            else
            {
                $data['_view'] = 'dcategory/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The dcategory you are trying to edit does not exist.');
    } 

    /*
     * Deleting dcategory
     */
    function remove($dtype)
    {
        if(!$this->auth->isDelete()){
            redirect('/');
        }
        $dcategory = $this->Dcategory_model->get_dcategory($dtype);

        // check if the dcategory exists before trying to delete it
        if(isset($dcategory['dtype']))
        {
            $this->Dcategory_model->delete_dcategory($dtype);
            redirect('dcategory/index');
        }
        else
            show_error('The dcategory you are trying to delete does not exist.');
    }
    
}
