<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doctype extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Doctype_model');
    } 

    /*
     * Listing of doctype
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('doctype/index?');
        $config['total_rows'] = $this->Doctype_model->get_all_doctype_count();
        $this->pagination->initialize($config);

        $data['doctype'] = $this->Doctype_model->get_all_doctype($params);
        
        $data['_view'] = 'doctype/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new doctype
     */
    function add()
    {   
        if(!$this->auth->isAdd()){
            redirect('/');
        }
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'name' => $this->input->post('name'),
				'warndays' => $this->input->post('warndays'),
            );
            
            $doctype_id = $this->Doctype_model->add_doctype($params);
            redirect('doctype/index');
        }
        else
        {            
            $data['_view'] = 'doctype/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a doctype
     */
    function edit($id)
    {   
        if(!$this->auth->isEdit()){
            redirect('/');
        }
        // check if the doctype exists before trying to edit it
        $data['doctype'] = $this->Doctype_model->get_doctype($id);
        
        if(isset($data['doctype']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'name' => $this->input->post('name'),
					'warndays' => $this->input->post('warndays'),
                );

                $this->Doctype_model->update_doctype($id,$params);            
                redirect('doctype/index');
            }
            else
            {
                $data['_view'] = 'doctype/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The doctype you are trying to edit does not exist.');
    } 

    /*
     * Deleting doctype
     */
    function remove($id)
    {
        if(!$this->auth->isDelete()){
            redirect('/');
        }
        $doctype = $this->Doctype_model->get_doctype($id);

        // check if the doctype exists before trying to delete it
        if(isset($doctype['id']))
        {
            $this->Doctype_model->delete_doctype($id);
            redirect('doctype/index');
        }
        else
            show_error('The doctype you are trying to delete does not exist.');
    }
    
}
