<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Email_list extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Emails_model');
    } 

    /*
     * Listing of emailgroups
     */
    function index()
    {
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('email_list/index?');
        $data['email_list'] = $this->Emails_model->getRows('customers');
        
        $data['_view'] = 'email_list/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new emailgroup
     */
    function add()
    {   
        
        
        
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $datax = array(
                'customer_name' => $this->input->post('customer_name'),
                'nationality' => $this->input->post('nationality'),
                'email' => $this->input->post('email'),
                'mobile' => $this->input->post('mobile'),
                'idcard' => $this->input->post('idcard'),
                'position' => $this->input->post('position'),
                'remarks' => $this->input->post('remarks'),    
            );
            
            $emaillist_id = $this->Emails_model->insert('customers', $datax);
            if($emaillist_id) {
                redirect('email_list/index');
            }else{
                $data['_view'] = 'email_list/add';
                $this->load->view('layouts/main',$data);
            }
        }
        else
        {            
            $data['_view'] = 'email_list/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a emailgroup
     */
    function edit($id)
    {   
        // check if the emailgroup exists before trying to edit it
        $data['email_list'] = $this->Emails_model->getRows('customers', array('where'=>array('id'=> $id)));
        $data['id']=$id;
        if(isset($data['email_list']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $datax = array(
                    'customer_name' => $this->input->post('customer_name'),
                    'nationality' => $this->input->post('nationality'),
                    'email' => $this->input->post('email'),
                    'mobile' => $this->input->post('mobile'),
                    'idcard' => $this->input->post('idcard'),
                    'position' => $this->input->post('position'),
                    'remarks' => $this->input->post('remarks'),  
                );

                $this->Emails_model->update('customers', $datax, array('id'=>$id));            
                redirect('email_list/index');
            }
            else
            {
                $data['_view'] = 'email_list/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The emailgroup you are trying to edit does not exist.');
    } 

    /*
     * Deleting emailgroup
     */
    function remove($id)
    {
        
        // check if the emailgroup exists before trying to delete it
        if(isset($id))
        {
            $this->Emails_model->delete('customers', $id);
            redirect('email_list/index');
        }
        else
            show_error('The emailgroup you are trying to delete does not exist.');
    }
    
}
