<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Letter extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Letter_model');
    } 

    /*
     * Listing of letters
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('letter/index?');
        $config['total_rows'] = $this->Letter_model->get_all_letters_count();
        $this->pagination->initialize($config);

        $data['letters'] = $this->Letter_model->get_all_letters($params);
        
        $data['_view'] = 'letter/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new letter
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('subject','Subject','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'mdate' => $this->input->post('mdate'),
				'sdate' => $this->input->post('sdate'),
				'recipients' => $this->input->post('recipients'),
				'subject' => $this->input->post('subject'),
            );
            
            $letter_id = $this->Letter_model->add_letter($params);
            redirect('letter/index');
        }
        else
        {            
            $data['_view'] = 'letter/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a letter
     */
    function edit($letterid)
    {   
        // check if the letter exists before trying to edit it
        $data['letter'] = $this->Letter_model->get_letter($letterid);
        
        if(isset($data['letter']['letterid']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('subject','Subject','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'mdate' => $this->input->post('mdate'),
					'sdate' => $this->input->post('sdate'),
					'recipients' => $this->input->post('recipients'),
					'subject' => $this->input->post('subject'),
                );

                $this->Letter_model->update_letter($letterid,$params);            
                redirect('letter/index');
            }
            else
            {
                $data['_view'] = 'letter/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The letter you are trying to edit does not exist.');
    } 

    /*
     * Deleting letter
     */
    function remove($letterid)
    {
        $letter = $this->Letter_model->get_letter($letterid);

        // check if the letter exists before trying to delete it
        if(isset($letter['letterid']))
        {
            $this->Letter_model->delete_letter($letterid);
            redirect('letter/index');
        }
        else
            show_error('The letter you are trying to delete does not exist.');
    }
    
}
