<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_group extends CI_Controller{
    function __construct(){
        parent::__construct();
        $this->load->model('User_group_model');
    }
}
