<?php
/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sendit extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->model('Emails_model');
//        $this->load->library('email');
        $this->load->library('encrypt');
    }

    /*
     * Listing of letters
     */

    function index($id=0) {
        
        if(($id==0)){ redirect('message/index', 'refresh'); die();}
      
        
        $settings = $this->Emails_model->getRows('emailsettings');
        $messagec = $this->Emails_model->getRows('message', array('where' => array('id' => $id)));
        $emails = $this->Emails_model->getRows('grdetails', array('where' => array('groupid' => $messagec[0]['mailto'])));
        
        
        
        
        if(count($messagec[0])==0){
        ?>
        <p>No valid Messages.</p>
        <script>
        setTimeout(function(){ window.location="<?php echo site_url() ?>message/index"; }, 3000);
        </script>
        <?php
            die();
        }
        

        
        
//        print_r($emails);

        //echo $attch; 
//die();



        $config['protocol'] = 'smtp';
        $config['smtp_host'] = $settings[0]['smtp_host'];
        $config['smtp_port'] = $settings[0]['smtp_port'];
        $config['smtp_user'] = $settings[0]['smtp_username'];
        $config['smtp_pass'] = $settings[0]['smtp_password'];


        $config['smtp_crypto'] = 'TLS';
        $config['mailtype'] = 'html';
        $config['smtp_timeout'] = '4';
        $config['charset'] = 'iso-8859-1';
        $config['wordwrap'] = TRUE;
        $config['newline'] = "\r\n";

        $this->load->library('email', $config);
        $this->email->set_newline("rn");
        

        
        $attch=  explode(',',$messagec[0]['attachments']);

        
        if($attch[0]){ 
            $attch1=FCPATH . 'assets/upload/'.$attch[0];
            $this->email->attach($attch1);
        
        }
        if($attch[1]){
            $attch2=FCPATH . 'assets/upload/'.$attch[1];
            $this->email->attach($attch2);
        }
        if($attch[2]){
            $attch3=FCPATH . 'assets/upload/'.$attch[2];
            $this->email->attach($attch3);
        }
        
        foreach ($emails as $em) {

            $subject = $messagec[0]['subject'];



            $this->email->from($settings[0]['smtp_username'], $settings[0]['smtp_username']);

            $this->email->subject($subject);



            $message = str_replace("{name}", $em['name'], $messagec[0]['content']);
            $this->email->to($em['email']);
            $this->email->cc($messagec[0]['mailcc']);
            $this->email->message($message);

            if ($this->email->send()) {
                echo 'Email Successfully send to ' . $em['email'] . '<br/>';
            } else {
                print_r($this->email);
            }
        }

        if($messagec[0]['toemail']){
            $subject = $messagec[0]['subject'];



            $this->email->from($settings[0]['smtp_username'], $settings[0]['smtp_username']);

            $this->email->subject($subject);



            $message = str_replace("{name}", $em['name'], $messagec[0]['content']);
            $this->email->to($messagec[0]['toemail']);
            $this->email->cc($messagec[0]['mailcc']);
            $this->email->message($message);

            if ($this->email->send()) {
//                echo 'Email Successfully send to ' . $messagec[0]['toemail'] . '<br/>';
            } else {
                print_r($this->email);
            }
        }

        $update = $this->Emails_model->update('message', array('status' => "send"), array('id' => $id));

        //redirect('message/index', 'refresh');
        //status
        echo 'Email Successfully send';
        ?>
        <script>

        setTimeout(function(){ window.location="<?php echo site_url() ?>message/index"; }, 3000);
        </script>

        <?php
    }

}
