<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Settings extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Emails_model');
    } 

    /*
     * Listing of emailgroups
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('emailgroup/index?');
        $config['total_rows'] = $this->Emails_model->get_all_emailgroups_count();
        $this->pagination->initialize($config);

        $data['settings'] = $this->Emails_model->getRows('emailsettings');
        
        $data['_view'] = 'settings/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new emailgroup
     */


    /*
     * Editing a emailgroup
     */
    function update()
    {   
        // check if the emailgroup exists before trying to edit it
        $data['smtp_host']=$this->input->post('smtp_host');
        $data['smtp_port']=$this->input->post('smtp_port');
        $data['smtp_username']=$this->input->post('smtp_username');
        $data['smtp_password']=$this->input->post('smtp_password');
        $data['max_group']=$this->input->post('max_group');
        
        if($this->input->post('id'))
        {
            $this->Emails_model->update('emailsettings', $data, array('id' => $this->input->post('id')));
            
        }
        else{
            $this->Emails_model->insert('emailsettings', $data);
        }
            redirect('settings/index');
    } 


    
}
