<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Company_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get company by companyid
     */
    function get_company($companyid)
    {
		
		 
		 
		 
		$this->db->select('C.companyid,C.Name,C.companyNo,C.CompType,C.CompReg,C.email,C.Managerid,C.Remarks');
		$this->db->from('company AS C');		
		$this->db->where('companyid',$companyid);
		$query=$this->db->get();
		return $data=$query->row_array();

				 
		 
		 
		 
		
        //return $this->db->get_where('company',array('companyid'=>$companyid))->row_array();
    }
    
	
	
	
	 function get_companyprofile($companyid)
    {
       // return $this->db->get_where('company',array('companyid'=>$companyid))->row_array();
//	   $this->db->select('C.companyid,C.Name,C.companyNo,C.CompType,C.CompReg,C.email,C.Managerid,C.Remarks');
	//	$this->db->from('company AS C');		
	//	$this->db->where('companyid',$companyid);
	//	$query=$this->db->get();
	//	return $data=$query->row_array();
	  
	    $this->db->select('company.*, comptypes.Name AS comptypes_name, employees.emp_name AS manager_name');
        $this->db->from('company');
        $this->db->join('comptypes','company.CompType=comptypes.CompType','left');
        $this->db->join('employees','company.Managerid=employees.employee_id','left');
        $this->db->where('company.companyid', $companyid);
    //    return $this->db->get()->result_array();	
			$query=$this->db->get();
		return $data=$query->row_array();
    }
	
    /*
     * Get all company count
     */
    function get_all_company_count($value=null)
    {
        $this->db->from('company');
		if(!empty($value)){
			$this->db->like('Name',$value);
		}		
		
        return $this->db->count_all_results();
		
		
    }
        
    /*
     * Get all company
     */
    function get_all_company($params = array())
    {
        $this->db->order_by('Name', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        //return $this->db->get('company')->result_array();
	  
        $this->db->select('company.companyid,company.Name,company.companyNo ,company.CompType,company.CompReg,company.email,company.Managerid,comptypes.name as CTypeName');
		
        $this->db->from('company');
  
      //  $this->db->join('employees','company.Managerid=employees.employee_id','inner');
        $this->db->join('comptypes','company.CompType=comptypes.CompType','inner');
        $newval=$this->db->get()->result_array();
		$new_arr=array();
		if(!empty($newval)){
			
			foreach($newval as &$new_arr){
				
				    $this->db->select('G.customer_id,C.Customer_name,C.Nationality,C.email,C.mobile,C.IDcard,C.Position,C.Remarks,G.companyid,G.id');
					 $this->db->from('get_company AS G');
				     $this->db->join('customers AS C','C.customer_id=G.customer_id');
					 $this->db->where('G.companyid',$new_arr['companyid']);
					 $new_arr['customers']=$this->db->get()->result_array();
      
			}
		}
		
		return $newval;
    }
    
    function get_companies_by_customer_id($customer_id){
        $this->db->select('company.*, comptypes.Name AS comptypes_name, employees.emp_name AS manager_name, employees.mobile AS manager_mobile');
        $this->db->from('company');
        $this->db->join('comptypes','company.CompType=comptypes.CompType','left');
        $this->db->join('employees','company.Managerid=employees.employee_id','left');
        $this->db->where('company.Customer_id', $customer_id);
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new company
     */
    function add_company($params)
    {
        $this->db->insert('company',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update company
     */
    function update_company($companyid,$params)
    {
        $this->db->where('companyid',$companyid);
        return $this->db->update('company',$params);
    }
    
    /*
     * function to delete company
     */
    function delete_company($companyid)
    {
        return $this->db->delete('company',array('companyid'=>$companyid));
    }
    
    
    public function count_company_by_customer_id($customer_id){
        $this->db->from('company');
        $this->db->where('Customer_id', $customer_id);
        return $this->db->count_all_results();
    }
}
