<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comptype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comptype by CompType
     */
    function get_comptype($CompType)
    {
        return $this->db->get_where('comptypes',array('CompType'=>$CompType))->row_array();
    }
    
    /*
     * Get all comptypes count
     */
    function get_all_comptypes_count()
    {
        $this->db->from('comptypes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all comptypes
     */
    function get_all_comptypes($params = array())
    {
        $this->db->order_by('CompType', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('comptypes')->result_array();
    }
        
    /*
     * function to add new comptype
     */
    function add_comptype($params)
    {
        $this->db->insert('comptypes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comptype
     */
    function update_comptype($CompType,$params)
    {
        $this->db->where('CompType',$CompType);
        return $this->db->update('comptypes',$params);
    }
    
    /*
     * function to delete comptype
     */
    function delete_comptype($CompType)
    {
        return $this->db->delete('comptypes',array('CompType'=>$CompType));
    }
}
