<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Customer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get customer by customer_id
     */
    function get_customer($customer_id)
    {
        return $this->db->get_where('customers',array('customer_id'=>$customer_id))->row_array();
    }
    
    /*
     * Get all customers count
     */
    function get_all_customers_count($value=null)
    {
      		
		$this->db->from('customers');
		if(!empty($value)){
			$this->db->like('Customer_name',$value);
		}
        return $this->db->count_all_results();
    }
        
    /*
     * Get all customers
     */
    function get_all_customers($params = array())
    {
        $this->db->order_by('Customer_name', 'asc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('customers')->result_array();
    }
        
    /*
     * function to add new customer
     */
    function add_customer($params)
    {
        $this->db->insert('customers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update customer
     */
    function update_customer($customer_id,$params)
    {
        $this->db->where('customer_id',$customer_id);
        return $this->db->update('customers',$params);
    }
    
    /*
     * function to delete customer
     */
    function delete_customer($customer_id)
    {
        return $this->db->delete('customers',array('customer_id'=>$customer_id));
    }
	
	
	 public function count_customer_by_company_id($companyid){
        $this->db->from('customers');
        $this->db->where('companyid', $companyid);
        return $this->db->count_all_results();
    }
}
