<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dcategory_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dcategory by dtype
     */
    function get_dcategory($dtype)
    {
        return $this->db->get_where('dcategory',array('dtype'=>$dtype))->row_array();
    }
        
    /*
     * Get all dcategory
     */
    function get_all_dcategory()
    {
        $this->db->order_by('dtype', 'desc');
        return $this->db->get('dcategory')->result_array();
    }
        
    /*
     * function to add new dcategory
     */
    function add_dcategory($params)
    {
        $this->db->insert('dcategory',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dcategory
     */
    function update_dcategory($dtype,$params)
    {
        $this->db->where('dtype',$dtype);
        return $this->db->update('dcategory',$params);
    }
    
    /*
     * function to delete dcategory
     */
    function delete_dcategory($dtype)
    {
        return $this->db->delete('dcategory',array('dtype'=>$dtype));
    }
}
