<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doctype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get doctype by id
     */
    function get_doctype($id)
    {
        return $this->db->get_where('doctype',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all doctype count
     */
    function get_all_doctype_count()
    {
        $this->db->from('doctype');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all doctype
     */
    function get_all_doctype($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('doctype')->result_array();
    }
        
    /*
     * function to add new doctype
     */
    function add_doctype($params)
    {
        $this->db->insert('doctype',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update doctype
     */
    function update_doctype($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('doctype',$params);
    }
    
    /*
     * function to delete doctype
     */
    function delete_doctype($id)
    {
        return $this->db->delete('doctype',array('id'=>$id));
    }
}
