<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Emailgroup_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get emailgroup by groupid
     */
    function get_emailgroup($groupid)
    {
        return $this->db->get_where('emailgroups',array('groupid'=>$groupid))->row_array();
    }
    
    /*
     * Get all emailgroups count
     */
    function get_all_emailgroups_count()
    {
        $this->db->from('emailgroups');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all emailgroups
     */
    function get_all_emailgroups($params = array())
    {
        $this->db->order_by('groupid', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('emailgroups')->result_array();
    }
        
    /*
     * function to add new emailgroup
     */
    function add_emailgroup($params)
    {
        $this->db->insert('emailgroups',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update emailgroup
     */
    function update_emailgroup($groupid,$params)
    {
        $this->db->where('groupid',$groupid);
        return $this->db->update('emailgroups',$params);
    }
    
    /*
     * function to delete emailgroup
     */
    function delete_emailgroup($groupid)
    {
        return $this->db->delete('emailgroups',array('groupid'=>$groupid));
    }
}
