<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Emptype_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get emptype by Ctype
     */
    function get_emptype($Ctype)
    {
        return $this->db->get_where('emptypes',array('Ctype'=>$Ctype))->row_array();
    }
    
    /*
     * Get all emptypes count
     */
    function get_all_emptypes_count()
    {
        $this->db->from('emptypes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all emptypes
     */
    function get_all_emptypes($params = array())
    {
        $this->db->order_by('Ctype', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('emptypes')->result_array();
    }
        
    /*
     * function to add new emptype
     */
    function add_emptype($params)
    {
        $this->db->insert('emptypes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update emptype
     */
    function update_emptype($Ctype,$params)
    {
        $this->db->where('Ctype',$Ctype);
        return $this->db->update('emptypes',$params);
    }
    
    /*
     * function to delete emptype
     */
    function delete_emptype($Ctype)
    {
        return $this->db->delete('emptypes',array('Ctype'=>$Ctype));
    }
}
