<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_group_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_group by user_group_id
     */
    function get_user_group($user_group_id)
    {
        return $this->db->get_where('user_group',array('user_group_id'=>$user_group_id))->row_array();
    }
        
    /*
     * Get all user_group
     */
    function get_all_user_group()
    {
        $this->db->order_by('user_group_id', 'desc');
        return $this->db->get('user_group')->result_array();
    }
        
    /*
     * function to add new user_group
     */
    function add_user_group($params)
    {
        $this->db->insert('user_group',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_group
     */
    function update_user_group($user_group_id,$params)
    {
        $this->db->where('user_group_id',$user_group_id);
        return $this->db->update('user_group',$params);
    }
    
    /*
     * function to delete user_group
     */
    function delete_user_group($user_group_id)
    {
        return $this->db->delete('user_group',array('user_group_id'=>$user_group_id));
    }
}
